# Site settings
title: Infinite Dango Studios
email: cwellsny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Infinite Dango Studio is a game devlopment studio that is currently working on the development of the open source, visual novel Ganbatte.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://infinite-dango-studios.github.io/" # the base hostname & protocol for your site
twitter_username: infinite-dange-studios
github_username:  Infinite-Dango-Studios

# Build settings
markdown: kramdown
